#!/usr/bin/env python

import sys
from platform_methods import run_in_subprocess
import platform_server_builders

Import("env")

common_server = [
    "os_server.cpp",
]

if sys.platform == "darwin":
    common_server.append("#platform/osx/crash_handler_osx.mm")
    common_server.append("#platform/osx/power_osx.cpp")
else:
    common_server.append("#platform/x11/crash_handler_x11.cpp")
    common_server.append("#platform/x11/power_x11.cpp")

prog = env.add_program("#bin/godot_server", ["godot_server.cpp"] + common_server)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    if sys.platform == "darwin":
        env.AddPostAction(prog, run_in_subprocess(platform_server_builders.make_debug_osx))
    else:
        env.AddPostAction(prog, run_in_subprocess(platform_server_builders.make_debug_x11))
